OptcRestApi\Components\Character\Entity\Character:
    exclusion_policy: ALL
    access_type: property
    read_only: false
    properties:
        id:
            type: integer
            expose: true
            groups: [api]
        name:
            type: string
            expose: true
            groups: [api]
        experience:
            type: integer
            expose: true
            groups: [api]
        description:
            type: string
            expose: true
            groups: [api]
        maxLevel:
            type: integer
            expose: true
            groups: [api]
        rarity:
            type: integer
            expose: true
            groups: [api]
        cost:
            type: integer
            expose: true
            groups: [api]
        combo:
            type: integer
            expose: true
            groups: [api]