rest:
    resource: "@RESTBundle/Resources/config/routing.yml"
    prefix: /
    defaults: {_format: json}

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user:
    resource: "fos_user.yml"
    prefix: /