OptcRestApi\Components\OAuth\Entity\AccessToken:
    type: entity
    repositoryClass: ~
    table: access_token
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 255
    manyToOne:
        client:
            targetEntity: OptcRestApi\Components\OAuth\Entity\Client
            joinColumn:
                nullable: false