OptcRestApi\Components\OAuth\Entity\AuthCode:
    type: entity
    repositoryClass: ~
    table: auth_code
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: OptcRestApi\Components\OAuth\Entity\Client
            joinColumn:
                nullable: false