OptcRestApi\Components\OAuth\Entity\AuthCode:
    type: entity
    repositoryClass: ~
    table: auth_code
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        redirectUri:
            column: redirect_uri
            type: string
            length: 255
    manyToOne:
        client:
            targetEntity: OptcRestApi\Components\OAuth\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: OptcRestApi\Components\User\Entity\User
            joinColumn:
                nullable: false