OptcRestApi\Components\OAuth\Entity\Client:
    type: entity
    repositoryClass: ~
    table: client
    id:
        id:
            type: integer
            generator:
                strategy: AUTO