OptcRestApi\Components\OAuth\Entity\RefreshToken:
    type: entity
    repositoryClass: ~
    table: refresh_token
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 255
        expiresAt:
            type: integer
        scope:
            type: string
            length: 255
            nullable: true
    manyToOne:
        client:
            targetEntity: OptcRestApi\Components\OAuth\Entity\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: OptcRestApi\Components\User\Entity\User
            joinColumn:
                nullable: false