OptcRestApi\Components\User\Entity\User:
    type: entity
    repositoryClass: ~
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        email:
            type: string
            length: 255
        enabled:
            type: boolean
        salt:
            type: string
            length: 255
        password:
            type: string
            length: 255
        name:
            type: string
            length: 255
        surnames:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
