login_check:
    path: login_check

user:
    resource: "@RESTBundle/Resources/config/routing/user.yml"
    prefix: /user

test_api:
    path: /test-api
    defaults:
        _controller: RESTBundle:Users/User:testApi
