login_check:
    path: login_check

user:
    resource: "@RESTBundle/Resources/config/routing/user.yml"
    prefix: /users

character:
    resource: "@RESTBundle/Resources/config/routing/character.yml"
    prefix: /characters