services:
    optc_api.repository.character:
        class: 'OptcRestApi\Components\Character\Entity\CharacterRepository'
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - OptcRestApi\Components\Character\Entity\Character