services:
    optc_api.repository.character:
        class: 'OptcRestApi\Components\Character\Entity\CharacterRepository'
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - OptcRestApi\Components\Character\Entity\Character

    optc_api.entity_merger:
        class: 'OptcRestApi\Bundles\RESTBundle\Service\ExtenderEntityMerger'
        arguments:
            - @serializer
            - @doctrine.orm.default_entity_manager